# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Titel')),
                ('blutwert', models.IntegerField(verbose_name='Blutwert')),
                ('slug', models.SlugField(unique=True)),
                ('restinsulin', models.IntegerField(verbose_name='Restinsulin')),
                ('kohlenhydrate', models.IntegerField(verbose_name='Kohlenhydrate')),
                ('vorschlagInsulin', models.IntegerField(verbose_name='Vorschlag wie viel Einheiten Insulin')),
                ('kommentar', models.TextField(max_length=200, verbose_name='Kommentar')),
                ('werteinschaetzung', models.SmallIntegerField(choices=[(1, 'Gut'), (2, 'Mittel'), (3, 'Schlecht')], default=2, verbose_name='Wert Einschätzung')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ManyToManyField(to='myapp.Category', verbose_name='Kategorien')),
            ],
            options={
                'verbose_name': 'Insulin Einheit',
                'verbose_name_plural': 'Insuline Einheiten',
                'ordering': ['-date_created'],
            },
        ),
    ]
